apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../rbac
- ../crd
- ../manager
# patchesStrategicMerge:
# - deployment-patch.yaml
patches:
 - target:
      group: apps
      version: v1
      kind: Deployment
      name: manager
   path: deployment-patch.yaml
