apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dcontroller-manager-system
resources:
- ../rbac
- ../crd
- ../manager
namePrefix: dcontroller-
patches:
 - target:
      group: apps
      version: v1
      kind: Deployment
      name: manager
   path: deployment-patch.yaml
