apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- manager.yaml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
- files:
  - manager_config.yaml
  name: manager-config
images:
- name: controller
  newName: rg0now/dcontroller
  newTag: latest
