apiVersion: dcontroller.io/v1alpha1
kind: Operator
metadata:
  name: pod-container-num-annotator
spec:
  controllers:                                         # operator is a set of controllers
    - name: pod-container-num-annotator
      sources:
        - apiGroup: ""                                 # operating on corev1
          kind: Pod                                    # watch corev1.Pod
          # namespace: default                         # could filter namespaces here too
      pipeline:                                        # run this pipeline
        "@aggregate":                                  
          - "@select":                                 # filter for pods in the default namesapce
              '@eq':                                   
                - "$.metadata.namespace"               
                - default                              # for each pod in the default namespace
          - "@project":                                
              metadata:                                
                name: "$.metadata.name"                # copy metadata.namespace and metadata.name
                namespace: "$.metadata.namespace"      
                annotations:                           
                  "dcontroller.io/container-num":      # add a new annotation indicating the number of containers
                    '@string':                         # force string conversion (annotation must be a string)
                      '@len': ["$.spec.containers"]    # value is the length of .spec.containers
      target:                                          
        apiGroup: ""                                   # patch corev1.Pod with the results
        kind: Pod
        type: Patcher
