apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: configdeployments.dcontroller.io
spec:
  group: dcontroller.io
  names:
    kind: ConfigDeployment
    listKind: ConfigDeploymentList
    plural: configdeployments
    singular: configdeployment
    shortNames:
      - configdeps
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required:
            - spec
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                configMap:
                  type: string
                deployment:
                  type: string
